"""models

Revision ID: 3e8619a14172
Revises:
Create Date: 2025-08-10 13:59:41.096529

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e8619a14172"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "citys",
        sa.Column("city_name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("city_name"),
    )
    op.create_table(
        "distances",
        sa.Column("city_from", sa.Integer(), nullable=True),
        sa.Column("city_to", sa.Integer(), nullable=True),
        sa.Column("distance", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_from"],
            ["citys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["city_to"],
            ["citys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("distances")
    op.drop_table("citys")
    # ### end Alembic commands ###
